# Tarefa 02

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [2]:
# 1) Seu código aqui | Calcule o percentual de acerto dos alunos por assunto.
mat = df_mat / 24 *100
por = df_por / 18 * 100
geo = df_geo / 8 * 100
ing = df_ing / 8 * 100
his = df_his / 8 * 100
fis = df_fis / 12 * 100
qui = df_qui / 12 * 100
pd.options.display.float_format = '{:.2f}'.format

In [10]:
# 2) Seu código aqui | Calcule o total de acertos de cada aluno.
acertos = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui

    Qt_acertos
0           35
1           48
2           50
3           32
4           30
..         ...
95          34
96          27
97          40
98          40
99          42

[100 rows x 1 columns]

In [4]:
# 3) Seu código aqui | Calcule o porcentual geral de cada aluno.
per_geral = acertos / 90 * 100

In [12]:
# 4) Seu código aqui | Suponha que a nota de corte para a segunda fase seja 45. 
#Quantos alunos tiveram nota maior que 45?
#segundaFase = acertos > 45
#segundaFase.sum()
segundaFase = acertos['Qt_acertos'] > 45
segundaFase
segundaFase.sum()

31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [34]:
a = df_mat.index[df_mat['Qt_acertos'] == 0].tolist()
b = df_fis.index[df_fis['Qt_acertos'] == 0].tolist()
c = df_qui.index[df_qui['Qt_acertos'] == 0].tolist()
d = []

for elemento in a:
    d.append(elemento)

for elemento in b:
    if elemento not in d:
        d.append(elemento)
for elemento in c:
    if elemento not in d:
        d.append(elemento)
d = sorted(d, key=int)

print("Os alunos que zeraram em Matemática, Física ou Química foram:", len(d))

Os alunos que zeraram em Matemática, Física ou Química foram: 23

In [35]:
max = len(d)
i = 0
mat = []
fis = []
qui = []
while i <= max:
  mat.append(df_mat.iloc[i])
  fis.append(df_fis.iloc[i])
  qui.append(df_qui.iloc[i])
  i += 1
junto = pd.DataFrame(np.column_stack([mat, fis, qui]), 
                               columns=['mat', 'fis', 'qui'])
junto

    mat  fis  qui
0     6    8    3
1    19   11    8
2    14    4    4
3    10    0    8
4     7    9    3
5    20    9    9
6     6    0    4
7    18    1    8
8    22    5    7
9    10    8    2
10   10    7    0
11   23    4    2
12   20    0    3
13    3    6    1
14    7    4    0
15   23    5    6
16    2    6    7
17   21    2    6
18   20   11    4
19    1    9   11
20   23    2    0
21   11    4    6
22    5    5    6
23    1    8    8

In [36]:
#Qual a média desses alunos em história e geografia?
max = len(d)
i = 0
his = []
geo = []
while i <= max:
  his.append(df_his.iloc[i])
  geo.append(df_geo.iloc[i])
  i += 1
junto = pd.DataFrame(np.column_stack([his, geo]), 
                               columns=['his', 'geo'])
junto['Média de História'] = junto['his']*100/8
junto['Média de Geografia'] = junto['geo']*100/8
del junto['his']
del junto['geo']
junto

    Média de História  Média de Geografia
0               12.50               87.50
1                0.00                0.00
2               87.50                0.00
3                0.00               37.50
4                0.00               25.00
5               25.00               62.50
6               62.50               87.50
7               87.50               50.00
8               75.00               25.00
9               50.00               37.50
10              12.50               37.50
11              75.00               25.00
12              12.50               37.50
13              25.00               25.00
14              12.50               12.50
15               0.00               25.00
16              87.50               75.00
17              50.00               25.00
18              37.50               37.50
19              12.50               87.50
20              75.00               75.00
21               0.00               37.50
22              37.50                0.00
23              50.00                0.00

In [46]:
#Monte um DataFrame com os alunos que passaram para a segunda fase. 
#Repare que estes alunos não podem ter sido desqualificados.
#lista com quem não passou
max = len(d)
i = 0
segundaFaseTotal = []
while i <= max:
    linha_da_vez = segundaFase.iloc[i] #como acessar só o true ou false?????
    print(linha_da_vez)
    if linha_da_vez is True:
        print('entrou')
        if i not in d:
          segundaFaseTotal.append(i)
        print('entrou')
    i += 1
print('Lista de alunos que irão para a segunda fase:')
print(segundaFaseTotal)

Qt_acertos    False
Name: 0, dtype: bool
Qt_acertos    True
Name: 1, dtype: bool
Qt_acertos    True
Name: 2, dtype: bool
Qt_acertos    False
Name: 3, dtype: bool
Qt_acertos    False
Name: 4, dtype: bool
Qt_acertos    True
Name: 5, dtype: bool
Qt_acertos    False
Name: 6, dtype: bool
Qt_acertos    True
Name: 7, dtype: bool
Qt_acertos    True
Name: 8, dtype: bool
Qt_acertos    False
Name: 9, dtype: bool
Qt_acertos    False
Name: 10, dtype: bool
Qt_acertos    False
Name: 11, dtype: bool
Qt_acertos    False
Name: 12, dtype: bool
Qt_acertos    False
Name: 13, dtype: bool
Qt_acertos    False
Name: 14, dtype: bool
Qt_acertos    False
Name: 15, dtype: bool
Qt_acertos    False
Name: 16, dtype: bool
Qt_acertos    True
Name: 17, dtype: bool
Qt_acertos    True
Name: 18, dtype: bool
Qt_acertos    False
Name: 19, dtype: bool
Qt_acertos    True
Name: 20, dtype: bool
Qt_acertos    False
Name: 21, dtype: bool
Qt_acertos    False
Name: 22, dtype: bool
Qt_acertos    False
Name: 23, dtype: bool
Lista de alunos que irão para a segunda fase:
[]

In [49]:
df = df_mat

df = df.rename(columns={'Qt_acertos': 'matematica'})

df['portugues'] = df_por

df['geografia'] = df_geo

df['ingles'] = df_ing

df['historia'] = df_his

df['fisica'] = df_fis

df['quimica'] = df_qui

df

    matematica  portugues  geografia  ingles  historia  fisica  quimica
0            6          7          7       3         1       8        3
1           19         10          0       0         0      11        8
2           14         16          0       5         7       4        4
3           10          7          3       4         0       0        8
4            7          2          2       7         0       9        3
..         ...        ...        ...     ...       ...     ...      ...
95           6          4          7       1         4       9        3
96           8          1          4       6         1       4        3
97          23          5          0       2         4       1        5
98           0         10          3       1         5      10       11
99          11         15          0       1         6       7        2

[100 rows x 7 columns]

In [51]:
df_aprovados =   df[ (df_mat['Qt_acertos'] != 0) &

                      (df_fis['Qt_acertos'] != 0) &

                      (df_qui['Qt_acertos'] != 0) ]
print('Lista de alunos que irão para a segunda fase:')
print(df_aprovados)

Lista de alunos que irão para a segunda fase:
    matematica  portugues  geografia  ingles  historia  fisica  quimica
0            6          7          7       3         1       8        3
1           19         10          0       0         0      11        8
2           14         16          0       5         7       4        4
4            7          2          2       7         0       9        3
5           20          2          5       3         2       9        9
..         ...        ...        ...     ...       ...     ...      ...
93          12         16          5       5         6       6        6
95           6          4          7       1         4       9        3
96           8          1          4       6         1       4        3
97          23          5          0       2         4       1        5
99          11         15          0       1         6       7        2

[77 rows x 7 columns]

In [ ]:
#IDEIA 1 QUE N DEU CERTO
# seu código aqui
#realizar a construção do dataframe  de todos as matérias
#mat = df_mat.rename(columns={df_mat.columns[0]: 'Qt_acertos_mat'}) 
#fis = df_fis.rename(columns={df_fis.columns[0]: 'Qtd_acertos_fis'}) 
#qui = df_qui.rename(columns={df_qui.columns[0]: 'Qtd_acertos_qui'}) #
#frames = [mat, fis, qui]
  
#result = pd.concat(frames)
#dando errado pois, tão aparecendo NaN
#result

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?

In [1]:
arquivo = 'https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-05-23/uf%3DAC/part-00000-63e5bee2-3684-4286-b709-7fe85483b04e.c000.csv'

In [7]:
# 1) Sua solução aqui
df = pd.read_csv(arquivo)
df.head()

HTTPError: HTTP Error 403: Forbidden

## Impossível fazer 3) e 4) porque o link não pega

In [ ]:
# 2)

In [ ]:
# 3)

In [ ]:
# 3) solução alternativa

In [ ]:
# 4)

In [ ]:
# 5)

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [ ]:
# 1)

In [ ]:
# 2)

In [ ]:
# 3)

In [ ]:
# 4)

In [ ]:
# 5)